name: moneymoneymoney
description: Simplifying working with money
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
