name: moneymoneymoney
description: Simplifying working with money
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  intl:

dev_dependencies:
  pedantic: ^1.9.0
  test:
